# -*- coding: utf-8 -*-
"""MATPLOTLIB

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cluFVY0IsuGsAT8ISjRyvQ-d1yACs_7C
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

"""MATPLOATLIB BASIC



"""

x = np.linspace(0,5,11)
x

y = x**2
y

plt.plot(x,y)  #or plt.plot(y,x)
plt.xlabel('x axis')
plt.xlabel('y axis')

"""SUB PLOT IS MATPLOATLIB"""

plt.subplot(2,2,1)#convert canva into 2 rows and 2 column, third ploat inside() stand for selecting subcolumn value
plt.plot(x,y)
plt.subplot(2,2,2)
plt.plot(x,y)
plt.subplot(2,2,3)
plt.plot(x,y)
plt.subplot(2,2,4)
plt.plot(x**2,x**2)

plt.subplot(6,6,1)

"""OBJECT ORIENTED WAY"""

fig = plt.figure()#for selecting canvas
fig.add_axes([0.1,0.1,0.8,0.8])

fig = plt.figure()
axis = fig.add_axes([0.1,0.1,0.6,0.8])

fig = plt.figure()
axis1 = fig.add_axes([0.1,0.1,0.6,0.8])
axis1.plot(x,y)

axis2 = fig.add_axes([0.1,0.1,0.2,0.2])
axis.plot(x,y)

#set fixed size and dpi
fig = plt.figure(figsize=(20,8) , dpi =100)
axis1 = fig.add_axes([0.1,0.1,1,1])
axis1.plot(x,y)

"""TYPES OF PLOT"""

#1.scatter plot
plt.scatter(x,y)

#2. Histogram plot
from random import sample
data = sample(range(1,1000),100)
plt.hist(data)

#3. boxplot
plt.boxplot(data)

"""Saving plot"""

fig = plt.figure()
axis1 = fig.add_axes([0.1,0.1,0.6,0.8])
axis1.plot(x,y)

plt.savefig("Basicplot.png")



"""Work with image"""

import matplotlib.image as mpimg
img = mpimg.imread("image..name")
plt.imshow(img)

"""optional designing"""

import matplotlib.pyplot as plt

plt.plot(x, y, color="pink")
plt.show()

